openmultiplechoice/openmultiplechoice

- README.md
Also, remove dead Discord link in text.
> README: update planned date for first alpha release

- resources/views/deck-editor.blade.php
> deck-editor: allow edit of exam date

- README.md
Also, remove the placeholder link to the demo that doesn't exist yet.
> README: add links for questions and bug reports

- app/Http/Controllers/Api/DeckController.php
- app/Http/Controllers/DeckController.php
- app/Http/Controllers/DeckSubmissionController.php
- app/Models/Deck.php
- app/Models/DeckSubmission.php
- app/Models/User.php
- database/migrations/2024_03_01_174346_create_deck_submissions_table.php
- database/seeders/DemoSeeder.php
- resources/views/deck-editor.blade.php
- resources/views/deck-submissions.blade.php
- resources/views/deck.blade.php
- resources/views/layouts/app.blade.php
- routes/web.php
where a deck can be submitted for review by an admin or moderator and then to be shown to all users in the create session view.
TODO / open questions:
closes #735
> Add basic deck submission workflow

- app/Http/Controllers/Api/MagicGIFController.php
- routes/api.php
- routes/web.php
> Update controller file names to comply with PSR-4 standard

- .env.example
- app/Console/Kernel.php
- app/Http/Controllers/AdminSettingsSignupController.php
- app/Http/Controllers/RegistrationController.php
- app/Http/Controllers/RegistrationTokenController.php
- app/Models/AdminSettingsSignup.php
- app/Models/RegistrationToken.php
- app/Models/User.php
- app/Rules/DomainRule.php
- config/app.php
- config/auth.php
- database/factories/RegistrationTokenFactory.php
- database/migrations/2024_03_29_160133_create_admin_settings_signup_table.php
- database/migrations/2024_04_02_225223_create_registration_tokens_table.php
- database/seeders/DemoUserSeeder.php
- resources/views/admin-settings-signup.blade.php
- resources/views/forgot-password.blade.php
- resources/views/layouts/app.blade.php
- resources/views/login.blade.php
- resources/views/registration-token.blade.php
- resources/views/resend-verification.blade.php
- resources/views/reset-password.blade.php
- resources/views/signup.blade.php
- resources/views/user-management.blade.php
- routes/web.php
> Add basic sign-up and password reset flows

- app/Console/Kernel.php
This prevents the "popular decks" section from disappearing from index by preventing a change of the keys in the `popularDecks` array (during data filtering) by using the `values()` function in the end. 
Also, the decks are ordered by session count.
Fixes #818
> Fix missing popular decks

- docs/tinker.md
Users now also need a verified email address to sign in. Update the example accordingly.
> docs/tinker: update "add user" example

- composer.json
- composer.lock
- config/purify.php
- resources/views/deck.blade.php
- resources/views/index.blade.php
- resources/views/info-single.blade.php
- resources/views/info.blade.php
- resources/views/messages.blade.php
- routes/web.php
Details in the commit messages.
> Switch from HTMLPurifier to Purify

- resources/views/deck-col-element.blade.php
- resources/views/deck-editor.blade.php
- resources/views/decks.blade.php
Also, resources/views/deck-editor: rename `Danger Zone` -> `Settings`.
> resources/views/decks: use separate list for archived decks

- app/Http/Controllers/QuestionController.php
- resources/views/layouts/app.blade.php
- resources/views/questions-reviewable.blade.php
- routes/web.php
Adds a view that lists all questions with the `needs_review` flag set and that are part of at least one public and writeable deck for users to discover and contribute to questions.
Closes #891
> Add view for questions that need review

- app/Console/Kernel.php
This changes the way the answer choices to be processed in the answer distribution stats calculation are retrieved from the database by reducing the data retrieved from the database to the needed minimum and doing as much data processing within the database backend as possible.
> Kernel.php: Improve performance of answer distribution stats

- .github/workflows/ci.yml
This adds a GitHub action that checks whether npm run build was run before the commit.
> .github/workflows: check for npm run build

- app/Http/Controllers/Api/DeckController.php
- app/Http/Controllers/SessionController.php
- database/factories/ModuleFactory.php
- tests/Feature/ApiDecksTest.php
- tests/Feature/UserManagementTest.php
Multiple fixups for https://github.com/openmultiplechoice/openmultiplechoice/commit/9db17d4db7d2319ed5b336d5b50dd1fc27fbc874 - details in the commits.
> Api/DeckController: fix query for public decks

- .mailmap
- app/Http/Controllers/Api/DeckBookmarkController.php
- app/Http/Controllers/Api/DeckController.php
- app/Http/Controllers/DeckController.php
- app/Models/Deck.php
- app/Models/User.php
- resources/views/deck-col-element.blade.php
- resources/views/deck.blade.php
> Fix bookmark loading and display

- app/Http/Controllers/Api/DeckController.php
- app/Http/Controllers/Api/ModuleController.php
- app/Http/Controllers/Api/SessionController.php
- app/Http/Controllers/Api/SubjectController.php
- app/Http/Controllers/SessionController.php
- tests/Feature/ApiDecksTest.php
- tests/Feature/ApiModulesTest.php
- tests/Feature/ApiSubjectsTest.php
- tests/Feature/SessionsTest.php
Details in the commit messages.
> Add missing authorization checks in a few handler methods

- app/Http/Controllers/DeckController.php
- resources/views/deck-editor.blade.php
- resources/views/deck-submissions.blade.php
- routes/web.php
Details in the commit messages.
> Deck settings usability updates

- app/Http/Controllers/Api/SessionController.php
- app/Models/Session.php
- database/migrations/2025_03_31_092317_fix_parent_session_id_foreign_key_constraints.php
- tests/Feature/SessionsTest.php
`database: fix parent_session_id foreign key constraints` contains the actual fix.
> Fix foreign key violation errors

- composer.lock
- resources/views/deck-question.blade.php
- resources/views/deck.blade.php
As always, details in the commit messages.
> Minor updates

- app/Http/Controllers/ModuleController.php
- app/Models/Deck.php
- resources/views/module.blade.php
Details in the commit messages.
> Filter module view decks list

- app/Console/Commands/CreateDummyDeck.php
- app/Http/Controllers/Api/QuestionController.php
- database/factories/AnswerChoiceFactory.php
Fixes #575 
Also adds a `AnswerChoiceFactory` and a custom artisan command to create dummy decks for testing.
>  Api/QuestionController: improve updating of answerChoices
