.github/workflows/issue-needs-triage-default-label.yml

Add a GitHub workflow that adds the "needs triage" label to all newly created issues.
https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues

Add .github/workflows/issue-needs-triage-default-label.yml

---

composer.json
composer.lock
docs/development.md

This adds [clockwork](https://underground.works/clockwork/) to the development requirements for composer. This adds the possibility to view
php dev tools and insights in the request processing in the browser
using the clockwork browser addon.

Add clockwork to `composer.json`

---

composer.json
composer.lock

Adds [doctrine/dbal](https://www.doctrine-project.org/projects/dbal.html) to the required packages in `composer.json` as is [needed for database population if sqlite is used](https://laravel.com/docs/10.x/migrations#modifying-columns-on-sqlite).

Add doctrine/dbal to `composer.json`

---

app/Http/Controllers/Api/DeckController.php
app/Http/Controllers/Api/DeckQuestionController.php
app/Http/Controllers/Api/SessionController.php
app/Http/Controllers/DeckController.php
app/Http/Controllers/DeckQuestionController.php
app/Http/Controllers/SessionController.php
database/migrations/2024_03_13_221040_deck_make_access_default_private.php
resources/views/deck-editor.blade.php
resources/views/deck.blade.php

So far the `access` attribute was mostly a stub and not yet editable by the user. Add a select element to the deck form to make it editable. Also change the default `access` to private so that user collections are private by default. Note that we don't plan to have private questions currently, i.e. only the collection of questions is private but not the contents of the individual questions in the deck.
Admins continue to be able to edit all decks, but we should add a warning to decks where the admin user isn't the owner to avoid accidental edits. (Will follow in a later commit.)
Also, add a few comments and extra lines to make the code more readable.

Make deck's `access` attribute editable and set default to 'private'

---

app/Http/Controllers/UserManagementController.php
app/Models/User.php
database/migrations/2024_03_24_164023_user_is_enabled_column.php
database/migrations/2024_03_24_164042_user_last_login_column.php
resources/views/layouts/app.blade.php
resources/views/user-management.blade.php
routes/web.php

This adds a basic user management table available for admins where they can toggle whether a user is enabled and view information for each user. The table will paginate and can be searched by email and name. This also disallows login for disabled users and records the time on each login (`last_login_at`).

Add basic user management

---

app/Http/Controllers/Api/SessionController.php
app/Models/Session.php
database/migrations/2024_05_08_123029_sessions_parent_session_column.php

This saves the parent session of derived sessions (e.g. "wrong answers from session x") in an additional database column.
Closes #763

Save parent session for derived sessions

---

app/Http/Controllers/Api/SessionController.php
app/Models/Deck.php
database/migrations/2024_05_19_154432_decks_parent_session_column.php

This saves the parent session of derived decks (e.g. "wrong answers from session x") in an additional database column. Related to #763 and 4f38128cb85ee17f60971e9c5501f75aefe367c1

Save parent session for derived decks

---

.gitattributes

Our Svelte code gets transpiled into non-readable minimized JavaScript into `public/build/assets/*`. Mark the path as "binary" via gitattributes to make git not show the opaque minimized version in diff views.
https://git-scm.com/docs/gitattributes#_marking_files_as_binary

gitattributes: mark built JavaScript files as "binary"

---

routes/web.php

This saves the `last_login_at` time for keycloak users like it is done for native users too.
Closes #929

routes/web.php: Last login time for keycloak users

---

app/Console/Kernel.php

In the scheduler for the answer stats calculation, only answer choices with related questions of the type MC should be retrieved by the database query. In the existing code, all answer choices would be queried, but only for those with MC type questions, the questions were eager-loaded. This lead to wrong answer choices being included in the collection and missing question objects.
This fixes this issue by actually only retrieving answer choices which are associated to questions of the type MC.

Kernel.php: Fix answer stats calculation

---

app/Models/User.php

The scope filter for the user model would not filter for the `name` attribute because of a typo. This commit fixes this.
Tested locally.

Models/User.php: Fix scope filter

---

resources/js/MessageView.svelte
resources/js/Messages.svelte
resources/views/messages.blade.php

This adds bootstraps `text-break` to divs where message content is handled to prevent long strings of text (e.g. links) from overflowing their containers.

Messages: Add boostraps `text-break` to divs

---

app/Http/Controllers/Api/DeckController.php
app/Http/Controllers/DeckController.php
resources/views/deck-editor.blade.php

This limits the metadata edits of `public-rw-listed` decks (name, exam date, module, description) to admins and moderators. Also enabled the un-listing of `public-rw-listed` decks by admins or moderators.
Closes #977

Limit metadata edits of `public-rw-listed` decks

---

app/Http/Controllers/DeckController.php
resources/views/deck-editor.blade.php

Currently, the module list can be confusing and ambiguous, with many modules or when modules have the same name (for example, multiple subjects with a module "introduction").
Resolves #1012

Use select optgroups to group modules into subjects

---

app/Models/Deck.php

Updated the relationship between Deck and Question models to include ordering by the pivot table's "created_at" column. This ensures questions are always retrieved in chronological order of their association with a deck.
Attempt to close #1053

Order deck questions by pivot creation date

---

README.md

a1d4021b2a7629f05990f620466253ebcd2f02a9 changed the README CI workflow badge to reflect the status for the master branch only, but the badge URL was wrong. Fix it.

README: fix link to CI workflow badge

---

app/Console/Kernel.php

The answer percentage can't be calculated for questions that were only answered by using "Show answer" (`answer_id` set to null) because the overall count of actual answer choices then is 0 and we cannot divide through 0 (`DivisionByZeroError`). Exclude answer choices without `answer_id` to fix this.
Closes #1070

Fix answer percentage calculation

---

database/migrations/2025_02_03_225606_create_indexes_on_answers_and_answer_choices.php

Add indexes to the `answers` and `answer_choices` tables for the columns
we frequently filter for or sort by, in particular when calculating the
answer distribution stats.
Follow-up for https://github.com/openmultiplechoice/openmultiplechoice/commit/68b8e328baa9e17c9cd728a59a31a370a27fc1e4
Resolves https://github.com/openmultiplechoice/openmultiplechoice/issues/1090

Add indexes to answers and answer_choices tables

---

app/Http/Controllers/DeckBookmarkController.php
app/Http/Controllers/DeckController.php
resources/views/decks-archived.blade.php
resources/views/decks.blade.php
routes/web.php

Paginate the `/decks` listing and move the list of archived decks to a seperate page `/decks/archived`.
Also, use the same page size (30) for decks, bookmarked decks and archived decks.
Resolves #1109

Paginate `/decks` listing

---

public/build/assets/Messages-AGQ0OQAU.js
public/build/assets/Messages-x0Aq4OLa.js
public/build/manifest.json
resources/js/Messages.js

Since 8565b2c455eb2a9955d22827e2c749373eda83da the Messages component uses the `questionContext.isAnswered` attribute to determine if comments should be displayed. Set `questionContext.isAnswered: true:` in Messages.js to show comments in the `question` and `deck-question` views.

Messages: set `questionContext.isAnswered: true` for question views

---

resources/views/deck-editor.blade.php
resources/views/deck-question.blade.php
resources/views/deck.blade.php

Currently, we show a message
This deck is listed under ...
for public decks in a module that are archived, but archived decks are never listed. Instead, show a message
This deck is archived. ...

resources/views/deck-editor: fix info message for archived decks
